version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: thefarma_api_nginx
    ports:
      - "80:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: thefarma_api
    command: bash -c "python manage.py migrate && gunicorn thefarmaapi.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: postgres:alpine
    container_name: postgres_thefarma
    volumes:
      - vol_postgres


