version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: thefarma_api_nginx
    ports:
      - "80:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static-data:/staticfiles
      - media-data:/mediafiles
    depends_on:
      - web

  web:
    build: .
    container_name: thefarma_api
    command: bash -c "python manage.py migrate && gunicorn thefarmaapi.wsgi:application -b 0.0.0.0:8000  --workers 3 --log-level=debug"
    volumes:
      - static-data:/thefarmaapi/staticfiles
      - media-data:/thefarmaapi/media
    expose:
      - "8000"
    environment:
     - DEBUG=False
     - BROKER_URL_INI=redis://api.thefarma.com.br:32768/0
     - DATABASE_URL=postgres://postgres:the183adminfarma@api.thefarma.com.br/api
     - DB_FIREBASE_URL=https://thefarma-f3206.firebaseio.com
     - DB_FIREBASE_AUTH_DOMAIN=thefarma-f3206.firebaseapp.com
     - DB_FIREBASE_API_KEY=5f1083d6039ac7599d435f45206efc766d2f1bcf
     - DB_FIREBASE_STORAGE_BUCKET=gs://thefarma-f3206.appspot.com
     - DB_FIREBASE_SERVICE_ACCOUNT=thefarma-5f1083d6039a.json
     - CORS_ORIGIN_WHITELIST=localhost:8000
     - CIELO_MERCHANT_ID=75f57cc2-dd9b-4464-bf40-3c2eeda97ec4
     - CIELO_MERCHANT_KEY=AVNXHCPNDASETGZGTQGIKIVTEECJMQSWDONXCLUA
     - CIELO_SANDBOX=True

  worker_default:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery --app=thefarmaapi._celery:app worker --loglevel=INFO --queues=default --hostname=worker_default"
    volumes:
      - media-data:/thefarmaapi/media
    environment:
     - DEBUG=False
     - BROKER_URL_INI=redis://api.thefarma.com.br:32768/0
     - DATABASE_URL=postgres://postgres:the183adminfarma@api.thefarma.com.br/api
     - DB_FIREBASE_URL=https://thefarma-f3206.firebaseio.com
     - DB_FIREBASE_AUTH_DOMAIN=thefarma-f3206.firebaseapp.com
     - DB_FIREBASE_API_KEY=5f1083d6039ac7599d435f45206efc766d2f1bcf
     - DB_FIREBASE_STORAGE_BUCKET=gs://thefarma-f3206.appspot.com
     - DB_FIREBASE_SERVICE_ACCOUNT=thefarma-5f1083d6039a.json
     - CORS_ORIGIN_WHITELIST=localhost:8000
     - CIELO_MERCHANT_ID=75f57cc2-dd9b-4464-bf40-3c2eeda97ec4
     - CIELO_MERCHANT_KEY=AVNXHCPNDASETGZGTQGIKIVTEECJMQSWDONXCLUA
     - CIELO_SANDBOX=True

  worker_update_cliente:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery --app=thefarmaapi._celery:app worker --autoscale=10,3 --loglevel=INFO --queues=update_cliente --hostname=worker_update_cliente"
    volumes:
      - media-data:/thefarmaapi/media
    environment:
     - DEBUG=False
     - BROKER_URL_INI=redis://api.thefarma.com.br:32768/0
     - DATABASE_URL=postgres://postgres:the183adminfarma@api.thefarma.com.br/api
     - DB_FIREBASE_URL=https://thefarma-f3206.firebaseio.com
     - DB_FIREBASE_AUTH_DOMAIN=thefarma-f3206.firebaseapp.com
     - DB_FIREBASE_API_KEY=5f1083d6039ac7599d435f45206efc766d2f1bcf
     - DB_FIREBASE_STORAGE_BUCKET=gs://thefarma-f3206.appspot.com
     - DB_FIREBASE_SERVICE_ACCOUNT=thefarma-5f1083d6039a.json
     - CORS_ORIGIN_WHITELIST=localhost:8000
     - CIELO_MERCHANT_ID=75f57cc2-dd9b-4464-bf40-3c2eeda97ec4
     - CIELO_MERCHANT_KEY=AVNXHCPNDASETGZGTQGIKIVTEECJMQSWDONXCLUA
     - CIELO_SANDBOX=True

  worker_propostas:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery --app=thefarmaapi._celery:app worker --autoscale=10,3 --loglevel=INFO --queues=propostas --hostname=worker_propostas"
    volumes:
      - media-data:/thefarmaapi/media
    environment:
     - DEBUG=False
     - BROKER_URL_INI=redis://api.thefarma.com.br:32768/0
     - DATABASE_URL=postgres://postgres:the183adminfarma@api.thefarma.com.br/api
     - DB_FIREBASE_URL=https://thefarma-f3206.firebaseio.com
     - DB_FIREBASE_AUTH_DOMAIN=thefarma-f3206.firebaseapp.com
     - DB_FIREBASE_API_KEY=5f1083d6039ac7599d435f45206efc766d2f1bcf
     - DB_FIREBASE_STORAGE_BUCKET=gs://thefarma-f3206.appspot.com
     - DB_FIREBASE_SERVICE_ACCOUNT=thefarma-5f1083d6039a.json
     - CORS_ORIGIN_WHITELIST=localhost:8000
     - CIELO_MERCHANT_ID=75f57cc2-dd9b-4464-bf40-3c2eeda97ec4
     - CIELO_MERCHANT_KEY=AVNXHCPNDASETGZGTQGIKIVTEECJMQSWDONXCLUA
     - CIELO_SANDBOX=True

volumes:
  static-data:
  media-data:
