version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: thefarma_api_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/ssl:/etc/certificates
      - ./config/nginx/gsdv.txt:/cert/gsdv.txt
      - static-data:/staticfiles
      - media-data:/mediafiles
    depends_on:
      - web

  web:
    build: .
    container_name: thefarma_api
    command: bash -c "python manage.py migrate && gunicorn thefarmaapi.wsgi:application -b 0.0.0.0:8000  --workers 3 --log-level=debug"
    volumes:
      - static-data:/thefarmaapi/staticfiles
      - media-data:/thefarmaapi/media
    expose:
      - "8000"
    environment:
     - DEBUG=False
     - BROKER_URL_INI=redis://api.thefarma.com.br:32768/0
     - DATABASE_URL=postgres://postgres:the183adminfarma@api.thefarma.com.br/api
     - DB_FIREBASE_URL=https://thefarma-f3206.firebaseio.com
     - DB_FIREBASE_AUTH_DOMAIN=thefarma-f3206.firebaseapp.com
     - DB_FIREBASE_API_KEY=5f1083d6039ac7599d435f45206efc766d2f1bcf
     - DB_FIREBASE_STORAGE_BUCKET=gs://thefarma-f3206.appspot.com
     - DB_FIREBASE_SERVICE_ACCOUNT=thefarma-5f1083d6039a.json
     - CORS_ORIGIN_WHITELIST=localhost:8000
     - CIELO_MERCHANT_ID=75f57cc2-dd9b-4464-bf40-3c2eeda97ec4
     - CIELO_MERCHANT_KEY=AVNXHCPNDASETGZGTQGIKIVTEECJMQSWDONXCLUA
     - CIELO_SANDBOX=True
     - REDIS_CHANNELS_HOST=api.thefarma.com.br
     - REDIS_CHANNELS_PORT=32769

  worker_default:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery --app=thefarmaapi._celery:app worker --autoscale=10,1 --loglevel=INFO --queues=default,update_cliente,propostas --hostname=worker_default"
    volumes:
      - media-data:/thefarmaapi/media
    environment:
     - DEBUG=False
     - BROKER_URL_INI=redis://api.thefarma.com.br:32768/0
     - DATABASE_URL=postgres://postgres:the183adminfarma@api.thefarma.com.br/api
     - DB_FIREBASE_URL=https://thefarma-f3206.firebaseio.com
     - DB_FIREBASE_AUTH_DOMAIN=thefarma-f3206.firebaseapp.com
     - DB_FIREBASE_API_KEY=5f1083d6039ac7599d435f45206efc766d2f1bcf
     - DB_FIREBASE_STORAGE_BUCKET=gs://thefarma-f3206.appspot.com
     - DB_FIREBASE_SERVICE_ACCOUNT=thefarma-5f1083d6039a.json
     - CORS_ORIGIN_WHITELIST=localhost:8000
     - CIELO_MERCHANT_ID=75f57cc2-dd9b-4464-bf40-3c2eeda97ec4
     - CIELO_MERCHANT_KEY=AVNXHCPNDASETGZGTQGIKIVTEECJMQSWDONXCLUA
     - CIELO_SANDBOX=True
     - REDIS_CHANNELS_HOST=api.thefarma.com.br
     - REDIS_CHANNELS_PORT=32769

  channels:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "daphne -e ssl::privateKey=/etc/certificates/thefarmaapi.key:certKey=/etc/certificates/thefarmaapi.crt -b 0.0.0.0 -p 8000 thefarmaapi.asgi:channel_layer"
    volumes:
      - media-data:/thefarmaapi/media
      - ./config/ssl:/etc/certificates
    expose:
      - "8000"
    environment:
     - DEBUG=False
     - BROKER_URL_INI=redis://api.thefarma.com.br:32768/0
     - DATABASE_URL=postgres://postgres:the183adminfarma@api.thefarma.com.br/api
     - DB_FIREBASE_URL=https://thefarma-f3206.firebaseio.com
     - DB_FIREBASE_AUTH_DOMAIN=thefarma-f3206.firebaseapp.com
     - DB_FIREBASE_API_KEY=5f1083d6039ac7599d435f45206efc766d2f1bcf
     - DB_FIREBASE_STORAGE_BUCKET=gs://thefarma-f3206.appspot.com
     - DB_FIREBASE_SERVICE_ACCOUNT=thefarma-5f1083d6039a.json
     - CORS_ORIGIN_WHITELIST=localhost:8000
     - CIELO_MERCHANT_ID=75f57cc2-dd9b-4464-bf40-3c2eeda97ec4
     - CIELO_MERCHANT_KEY=AVNXHCPNDASETGZGTQGIKIVTEECJMQSWDONXCLUA
     - CIELO_SANDBOX=True
     - REDIS_CHANNELS_HOST=api.thefarma.com.br
     - REDIS_CHANNELS_PORT=32769

volumes:
  static-data:
  media-data:
