# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('ibge', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('razao_social', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cliente_infog2', models.BooleanField(default=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=150)),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_responsavel', models.CharField(max_length=60)),
                ('sobrenome_responsavel', models.CharField(blank=True, max_length=60, null=True)),
                ('rg_responsavel', models.CharField(blank=True, max_length=14, null=True)),
                ('cpf_responsavel', models.CharField(max_length=11)),
                ('telefone_responsavel', models.CharField(max_length=11)),
                ('cep_responsavel', models.CharField(blank=True, max_length=8, null=True)),
                ('logradouro_responsavel', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_responsavel', models.IntegerField(blank=True, null=True)),
                ('bairro_responsavel', models.CharField(blank=True, max_length=150, null=True)),
                ('complemento_responsavel', models.CharField(blank=True, max_length=150, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmacias', to='api.Cidade')),
                ('cidade_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis_farmacias', to='api.Cidade')),
            ],
            options={
                'verbose_name': 'Farmácia',
                'verbose_name_plural': 'Farmácias',
            },
        ),
    ]
