# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 08:30
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160811_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nome_complementar',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
