# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 09:53
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160920_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uf',
            name='tabela_preco',
        ),
        migrations.AddField(
            model_name='tabelapreco',
            name='ufs',
            field=models.ManyToManyField(blank=True, to='api.Uf'),
        ),
    ]
