# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 22:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161028_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ('nome',), 'verbose_name': 'Laboratório', 'verbose_name_plural': 'Laboratórios'},
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Endereco'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nome',
            field=models.CharField(default='', max_length=110),
            preserve_default=False,
        ),
    ]
