# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 09:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161030_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apresentacao',
            name='tabela',
        ),
        migrations.AddField(
            model_name='tabelapreco',
            name='apresentacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tabelas', to='api.Apresentacao'),
            preserve_default=False,
        ),
    ]
