# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 10:09
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161031_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principioativo',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
