# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 21:51
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20161031_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='codigo_barras',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
