# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20161101_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabelapreco',
            old_name='icm',
            new_name='icms',
        ),
    ]
