# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20161101_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='apresentacoes'),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='data_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
