# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20161102_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
