# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 00:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20161111_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curtida',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='api.Post'),
        ),
        migrations.AlterField(
            model_name='curtida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
