# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 00:20
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20161118_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
