# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20161118_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
    ]
