# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 09:55
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
