# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 10:19
from __future__ import unicode_literals

import datetime

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_post_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='arquivos_atualizacao')),
            ],
            options={
                'verbose_name': 'Atualização',
                'verbose_name_plural': 'Atualizações',
            },
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 7, 386327), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bairro',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 14, 214456), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cidade',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 19, 323834), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 22, 730054), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 26, 683161), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 32, 855091), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='principioativo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 39, 26889), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representantelegal',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 41, 58094), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabelapreco',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 42, 808211), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uf',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 18, 45, 245662), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 2, 10, 19, 13, 417522), verbose_name='Data de atualização'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de atualização'),
        ),
    ]
