# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20161202_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao',
            name='arquivo',
            field=models.FileField(null=True, upload_to='arquivos_atualizacao'),
        ),
    ]
