# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 11:02
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20161202_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos_atualizacao'),
        ),
    ]
