# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 11:38
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1, null=True),
        ),
    ]
