# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 12:00
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20161206_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='razao_social',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
