# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_laboratorio_razao_social'),
        ('api', '0028_auto_20161214_1119'),
    ]

    operations = [
    ]
