# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 11:19
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20161216_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoApExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.IntegerField(blank=True, null=True)),
                ('principioAtivo_id', models.IntegerField()),
                ('classe', models.IntegerField(blank=True, null=True)),
                ('subClasse', models.IntegerField(blank=True, null=True)),
                ('laboratorio_id', models.IntegerField()),
                ('codbarras', models.CharField(blank=True, max_length=13, null=True)),
                ('codbarras2', models.CharField(blank=True, max_length=13, null=True)),
                ('codbarras3', models.CharField(blank=True, max_length=13, null=True)),
                ('tipoPreco', models.CharField(blank=True, max_length=1, null=True)),
                ('lista', models.CharField(blank=True, max_length=1, null=True)),
                ('vazio', models.CharField(blank=True, max_length=1, null=True)),
                ('generico', models.BooleanField()),
                ('descricao', models.CharField(max_length=100)),
                ('apresentacao', models.CharField(max_length=100)),
                ('dataVigencia', models.DateField(blank=True, null=True)),
                ('dataDesconhecida', models.DateField(blank=True, null=True)),
                ('pmf19', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pmf18', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pmf17', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pmf12', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pmc19', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pmc18', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pmc17', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pmc12', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('registroMS', models.CharField(blank=True, max_length=15, null=True)),
                ('portaria', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
