# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-24 19:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_medicamentoapexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'NOTÍCIA'), (1, 'PATROCINADO'), (2, 'AVISO')], default=0),
        ),
        migrations.AlterField(
            model_name='usuarioinstituicao',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_instituicao', to=settings.AUTH_USER_MODEL),
        ),
    ]
