# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0032_auto_20170104_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de atualização')),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Apresentacao')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Farmacia')),
            ],
        ),
        migrations.AlterModelOptions(
            name='atualizacao',
            options={'ordering': ['-id'], 'verbose_name': 'Atualização', 'verbose_name_plural': 'Atualizações'},
        ),
        migrations.AddField(
            model_name='atualizacao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='pmc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='pmf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
