# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 14:25
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20170306_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelapreco',
            name='ufs',
        ),
        migrations.AddField(
            model_name='uf',
            name='icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
