# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 23:28
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20170306_1655'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='perfil',
        #     name='celular',
        #     field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        # ),
    ]
