# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 00:37
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_perfil_celular'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='perfil',
        #     name='cpf',
        #     field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        # ),
    ]
