# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 14:51
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0044_auto_20170307_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioparceiro',
            old_name='instituicao',
            new_name='parceiro',
        ),
        migrations.AlterUniqueTogether(
            name='usuarioparceiro',
            unique_together=set([('parceiro', 'usuario')]),
        ),
    ]
