# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20170307_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apresentacao',
            old_name='medicamento',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'GENÉRICO'), (1, 'SIMILAR'), (2, 'ÉTICO'), (3, 'NÃO MEDICAMENTO')]),
        ),
    ]
