# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20170307_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Subsecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de atualização')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsecoes', to='api.Secao')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='secao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Secao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='subsecao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subsecao'),
        ),
    ]
