# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 11:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import api.models.apresentacao


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20170307_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemApresentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=api.models.apresentacao.generate_filename)),
            ],
        ),
        migrations.RemoveField(
            model_name='apresentacao',
            name='imagem',
        ),
        migrations.AddField(
            model_name='imagemapresentacao',
            name='apresentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='api.Apresentacao'),
        ),
    ]
