# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20170308_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laboratorio',
            new_name='Fabricante',
        ),
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ('nome',)},
        ),
    ]
