# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 11:44
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20170308_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de atualização')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='sintomas',
            field=models.ManyToManyField(blank=True, related_name='medicamentos_associados', to='api.Sintoma'),
        ),
    ]
