# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 13:46
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20170308_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='cliente_infog2',
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='farmacias'),
        ),
    ]
