# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_representantelegal_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='parceiros'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='site',
            field=models.URLField(blank=True, default='http://', null=True),
        ),
    ]
