# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 14:54
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20170308_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
