# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_post_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemapresentacao',
            name='capa',
            field=models.BooleanField(default=False),
        ),
    ]
