# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20170321_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='nome_destinatario',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='nome_endereco',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
