# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20170322_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Cliente',
        ),
    ]
