# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 15:19
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20170322_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sobre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
