# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20170322_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proprietario', models.CharField(max_length=60)),
                ('token', models.CharField(blank=True, max_length=160, null=True)),
                ('numero_cartão', models.CharField(max_length=4)),
                ('tipo', models.IntegerField(choices=[(0, 'CRÉDITO'), (1, 'DÉBITO')], default=0)),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3)])),
                ('bandeira', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Apresentacao')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('numero_parcelas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.IntegerField(choices=[(0, 'IDENTIFICAÇÃO'), (1, 'ENDEREÇO'), (2, 'PAGAMENTO'), (3, 'CONFIRMAÇÃO'), (4, 'FINALIZADO')], default=0)),
                ('remote_ip', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=50)),
                ('cartao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cartao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cliente')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Endereco')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pedido'),
        ),
    ]
