# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20170322_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='secao',
            name='imagem',
            field=models.ImageField(null=True, upload_to='secoes'),
        ),
    ]
