# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 18:11
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20170329_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
