# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 16:12
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20170329_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
