# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 17:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_clienteendereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteendereco',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Endereco'),
        ),
        migrations.AlterUniqueTogether(
            name='clienteendereco',
            unique_together=set([('_cliente', 'endereco')]),
        ),
    ]
