# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_perfil_cpf'),
        ('api', '0074_auto_20170411_1706'),
    ]

    operations = [
    ]
