# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 10:15
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_merge_20170717_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
