# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_cliente_celular'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tabelapreco',
            unique_together=set([('apresentacao', 'icms')]),
        ),
    ]
