# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_farmacia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='apresentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_vendidos', to='api.Apresentacao'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.Pedido'),
        ),
    ]
