# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20170727_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantelegal',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
