# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_representantelegal_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantelegal',
            name='celular',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
