# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 21:52
from __future__ import unicode_literals

from django.db import migrations, models

import api.models.pedido


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_representantelegal_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('remote_ip', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='remote_ip',
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.IntegerField(choices=[('CARTAO', 0), ('DINHEIRO', 1)], default=api.models.pedido.FormaPagamento(0)),
        ),
    ]
