# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 15:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import models, migrations

import api.models.enums.status_item
import api.models.enums.status_pedido
import api.models.enums.status_conta_receber
import api.models.enums.status_pagamento_cartao


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_migrate_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_adiantamento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Log')),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_credito_avista_farmacia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_credito_parcelado_farmacia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_credito_avista_thefarma', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_credito_parcelado_thefarma', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.IntegerField()),
                ('digito_agencia', models.CharField(max_length=1)),
                ('numero_conta', models.IntegerField()),
                ('digito_conta', models.CharField(max_length=1)),
                ('operacao', models.CharField(max_length=3, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_associadas', to='api.Banco')),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceberFarmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('ABERTA', 0), ('PAGA', 1), ('CANCELADA', 2)], default=api.models.enums.status_conta_receber.StatusContaReceber(0))),
                ('data_vencimento', models.DateField()),
                ('data_credito', models.DateField(null=True)),
                ('valor_adiantamento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_administradora_cartao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_thefarma', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_administradora_cartao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_thefarma', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('adiantamento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_adiantadas', to='api.Adiantamento')),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceberThefarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('ABERTA', 0), ('PAGA', 1), ('CANCELADA', 2)], default=api.models.enums.status_conta_receber.StatusContaReceber(0))),
                ('data_vencimento', models.DateField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_administradora_cartao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_administradora_cartao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_credito', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoCartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.IntegerField(choices=[('IDENTIFICACAO', 0), ('ENDERECO', 1), ('PAGAMENTO', 2), ('CONFIRMACAO', 3), ('FINALIZADO', 4)], default=api.models.enums.status_pagamento_cartao.StatusPagamentoCartao(0))),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api.Cartao')),
            ],
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='valor',
            new_name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cartao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.AddField(
            model_name='farmacia',
            name='percentual_etico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='percentual_generico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='percentual_nao_medicamentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='percentual_similar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='servico_entregador',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='servico_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='status',
            field=models.IntegerField(choices=[('ABERTO', 0), ('ENVIADO', 1), ('ENTREGUE', 2)], default=api.models.enums.status_item.StatusItem(0)),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_pedido', to='api.Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep',
            field=models.CharField(default=None, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_pedido', to='api.Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='log',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Log'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='logradouro',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_destinatario',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_endereco',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='api.Bairro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[('ABERTO', 0), ('ENVIADO', 1), ('ENTREGUE', 2), ('CANCELADO_PELA_FARMACIA', 3), ('CANCELADO_PELO_CLIENTE', 4)], default=api.models.enums.status_pedido.StatusPedido(0)),
        ),
        migrations.AddField(
            model_name='pagamentocartao',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='api.Pedido'),
        ),
        migrations.AddField(
            model_name='contareceberthefarma',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber_thefarma', to='api.Pedido'),
        ),
        migrations.AddField(
            model_name='contareceberfarmacia',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='api.Farmacia'),
        ),
        migrations.AddField(
            model_name='contareceberfarmacia',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber_farmacia', to='api.Pedido'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='conta_bancaria',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.ContaBancaria'),
            preserve_default=False,
        ),
    ]
