# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 17:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import api.models.enums.forma_pagamento
import api.models.enums.status_conta_receber
import api.models.enums.status_item
import api.models.enums.status_pagamento_cartao
import api.models.enums.status_pedido


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20170731_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceberfarmacia',
            name='adiantamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_adiantadas', to='api.Adiantamento'),
        ),
        migrations.AlterField(
            model_name='contareceberfarmacia',
            name='data_credito',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contareceberfarmacia',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTA'), (1, 'PAGA'), (2, 'CANCELADA')], default=api.models.enums.status_conta_receber.StatusContaReceber(0)),
        ),
        migrations.AlterField(
            model_name='contareceberthefarma',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTA'), (1, 'PAGA'), (2, 'CANCELADA')], default=api.models.enums.status_conta_receber.StatusContaReceber(0)),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTO'), (1, 'ENVIADO'), (2, 'ENTREGUE')], default=api.models.enums.status_item.StatusItem(0)),
        ),
        migrations.AlterField(
            model_name='pagamentocartao',
            name='status',
            field=models.IntegerField(choices=[(0, 'IDENTIFICACAO'), (1, 'ENDERECO'), (2, 'PAGAMENTO'), (3, 'CONFIRMACAO'), (4, 'FINALIZADO')], default=api.models.enums.status_pagamento_cartao.StatusPagamentoCartao(0)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.IntegerField(choices=[(0, 'CARTAO'), (1, 'DINHEIRO')], default=api.models.enums.forma_pagamento.FormaPagamento(0)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTO'), (1, 'ENVIADO'), (2, 'ENTREGUE'), (3, 'CANCELADO_PELA_FARMACIA'), (4, 'CANCELADO_PELO_CLIENTE')], default=api.models.enums.status_pedido.StatusPedido(0)),
        ),
    ]
