# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 18:40
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import api.models.enums.status_item_proposta


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_migrate_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPropostaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.IntegerField(choices=[(0, 'ABERTO'), (1, 'ENVIADO'), (2, 'CANCELADO')], default=api.models.enums.status_item_proposta.StatusItemProposta(0))),
                ('possui', models.BooleanField(default=True)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_propostos', to='api.Apresentacao')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.Farmacia')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_proposta', to='api.Pedido')),
            ],
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='farmacia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_vendidos', to='api.Farmacia'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together=set([('pedido', 'apresentacao', 'farmacia')]),
        ),
        migrations.AlterUniqueTogether(
            name='itempropostapedido',
            unique_together=set([('pedido', 'apresentacao', 'farmacia')]),
        ),
    ]
