# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 09:14
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20170802_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
