# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 09:35
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20170803_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='duracao_proposta',
            field=models.DurationField(default=datetime.timedelta(0, 300)),
        ),
    ]
