# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 11:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import models, migrations

import api.models.enums.status_pedido


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_configuracao_duracao_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempropostapedido',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_proposta', to='api.Farmacia'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTO'), (1, 'ACEITO'), (2, 'AGUARDANDO_ENVIO_FARMACIA'), (3, 'AGUARDANDO_RETIRADA_CLIENTE'), (4, 'ENVIADO'), (5, 'ENTREGUE'), (6, 'CANCELADO_PELA_FARMACIA'), (7, 'CANCELADO_PELO_CLIENTE'), (8, 'SEM_PROPOSTA'), (9, 'TIMEOUT')], default=api.models.enums.status_pedido.StatusPedido(0)),
        ),
    ]
