# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20170803_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
