# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_migrate_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
