# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20170811_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='uf',
            field=models.CharField(default='PI', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(max_length=150),
        ),
    ]
