# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20170811_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
