# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_configuracao_raio_proposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
    ]
