# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 10:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_remove_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentocartao',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api.Pedido'),
        ),
        migrations.AlterField(
            model_name='pagamentocartao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
