# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20170923_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmacia',
            old_name='horario_funcionamento_domindo_final',
            new_name='horario_funcionamento_domingo_final',
        ),
        migrations.RenameField(
            model_name='farmacia',
            old_name='horario_funcionamento_domindo_inicial',
            new_name='horario_funcionamento_domingo_inicial',
        ),
    ]
