# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 15:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20170930_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocartao',
            name='json_retorno',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
