# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 15:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_pagamentocartao_json_retorno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamentocartao',
            old_name='json_retorno',
            new_name='json_captura',
        ),
        migrations.AddField(
            model_name='pagamentocartao',
            name='json_venda',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
