# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 11:49
from __future__ import unicode_literals

import api.models.enums.status_item
import api.models.enums.status_pagamento_cartao
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20171004_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTO'), (1, 'ENVIADO'), (2, 'ENTREGUE'), (3, 'CANCELADO')], default=api.models.enums.status_item.StatusItem(0)),
        ),
        migrations.AlterField(
            model_name='pagamentocartao',
            name='status',
            field=models.IntegerField(choices=[(0, 'NAO_FINALIZADO'), (1, 'AUTORIZADO'), (2, 'PAGAMENTO_CONFIRMADO'), (3, 'NEGADO'), (10, 'CANCELADO'), (11, 'ESTORNADO'), (12, 'PENDENTE'), (13, 'ABORTADA'), (20, 'AGENDADA')], default=api.models.enums.status_pagamento_cartao.StatusPagamentoCartao(0)),
        ),
    ]
