# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 15:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_pedido_status_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempropostapedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
