# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_itempedido_quantidade_atendida'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContaReceberFarmacia',
            new_name='ContaPagar',
        ),
    ]
