# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20171023_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('percentual_credito_avista_farmacia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_credito_parcelado_farmacia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_credito_avista_thefarma', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_credito_parcelado_thefarma', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='percentual_credito_avista_farmacia',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='percentual_credito_avista_thefarma',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='percentual_credito_parcelado_farmacia',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='percentual_credito_parcelado_thefarma',
        ),
        migrations.AlterField(
            model_name='log',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='remote_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administradora',
            name='log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Log'),
        ),
    ]
