# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20171023_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='administradora_cartao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_pagos', to='api.Administradora'),
        ),
    ]
