# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 11:30
from __future__ import unicode_literals

import api.models.enums.status_pagamento_cartao
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_pedido_administradora_cartao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentocartao',
            name='cartao',
        ),
        migrations.RemoveField(
            model_name='pagamentocartao',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='captura_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cartao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='api.Cartao'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='farmacia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='api.Farmacia'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='json_captura',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='json_venda',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_parcelas',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagamento_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_cartao',
            field=models.IntegerField(choices=[(0, 'NAO_FINALIZADO'), (1, 'AUTORIZADO'), (2, 'PAGAMENTO_CONFIRMADO'), (3, 'NEGADO'), (10, 'CANCELADO'), (11, 'ESTORNADO'), (12, 'PENDENTE'), (13, 'ABORTADA'), (20, 'AGENDADA')], default=api.models.enums.status_pagamento_cartao.StatusPagamentoCartao(0)),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together=set([('pedido', 'apresentacao')]),
        ),
        migrations.DeleteModel(
            name='PagamentoCartao',
        ),
    ]
