# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20171023_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapagar',
            old_name='valor_bruto',
            new_name='valor_parcela',
        ),
        migrations.RenameField(
            model_name='contareceberthefarma',
            old_name='percentual_administradora_cartao',
            new_name='valor_parcela',
        ),
        migrations.RemoveField(
            model_name='contareceberthefarma',
            name='valor_administradora_cartao',
        ),
        migrations.RemoveField(
            model_name='contareceberthefarma',
            name='valor_bruto',
        ),
    ]
