# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 10:12
from __future__ import unicode_literals

import api.models.enums.status_conta_receber
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_auto_20171023_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'ABERTA'), (1, 'PAGA'), (2, 'CANCELADA')], default=api.models.enums.status_conta_receber.StatusContaReceber(0))),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_administradora_cartao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentual_administradora_thefarma', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_administradora_cartao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_administradora_thefarma', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('numero_parcela', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber_thefarma', to='api.Pedido')),
            ],
        ),
        migrations.RemoveField(
            model_name='contareceberthefarma',
            name='pedido',
        ),
        migrations.RenameField(
            model_name='contapagar',
            old_name='percentual_administradora_cartao',
            new_name='valor_liquido',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='adiantamento',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='data_credito',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='farmacia',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='percentual_thefarma',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='valor_adiantamento',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='valor_administradora_cartao',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='valor_parcela',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='valor_thefarma',
        ),
        migrations.AddField(
            model_name='administradora',
            name='dias_recebimento',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ContaReceberThefarma',
        ),
    ]
