# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:52
from __future__ import unicode_literals

import api.models.enums.status_item
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20171024_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contareceber',
            name='valor_administradora_cartao',
        ),
        migrations.RemoveField(
            model_name='contareceber',
            name='valor_administradora_thefarma',
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='api.Pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTO'), (1, 'CONFIRMADO'), (2, 'ENVIADO'), (3, 'ENTREGUE'), (4, 'CANCELADO')], default=api.models.enums.status_item.StatusItem(0)),
        ),
    ]
