# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_auto_20171024_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='percentual_etico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='percentual_generico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='percentual_nao_medicamentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='percentual_similar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
