# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 02:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20171110_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='horario_funcionamento_domingo_final',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário Domingos Final'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='horario_funcionamento_domingo_inicial',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário Domingos Inicial'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='horario_funcionamento_feriado_final',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário Feriados Final'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='horario_funcionamento_feriado_inicial',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário Feriados Inicial'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='horario_funcionamento_sabado_final',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário Sábados Final'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='horario_funcionamento_sabado_inicial',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário Sábados Inicial'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='horario_funcionamento_segunda_sexta_final',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário Dias Úteis Final'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='horario_funcionamento_segunda_sexta_inicial',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Horário Dias Úteis Inicial'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='percentual_etico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Percentual Éticos'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='percentual_generico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Percentual Genéricos'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='percentual_nao_medicamentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Percentual não Medicamentos'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='percentual_similar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Percentual Similares'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='razao_social',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='servico_entregador',
            field=models.BooleanField(default=True, verbose_name='Possui Entregador'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='servico_estoque',
            field=models.BooleanField(default=False, verbose_name='Habilitar Estoque'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='tempo_entrega',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Tempo de Entrega'),
        ),
    ]
