# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_auto_20171113_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='operacao',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ*'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='razao_social',
            field=models.CharField(max_length=100, verbose_name='Razão Social*'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone*'),
        ),
    ]
