# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_auto_20171113_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude*'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude*'),
        ),
    ]
