# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_auto_20171113_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
