# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_cartao_deletado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='ranking_compra',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='ranking_proposta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='ranking_visualizacao',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='peso_ranking_compra',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='peso_ranking_proposta',
            field=models.FloatField(default=1.25),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='peso_ranking_visualizacao',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='api.Cidade'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='ibge',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código IBGE'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Uf', verbose_name='UF'),
        ),
    ]
