# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_auto_20171201_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='patrocinio',
            field=models.BigIntegerField(default=0),
        ),
    ]
