# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_apresentacao_patrocinio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=15, unique=True)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=15, unique=True)),
                ('quantidade', models.IntegerField()),
                ('administradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelamentos', to='api.Administradora')),
            ],
        ),
    ]
