# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_parcelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='administradora',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Administradora'),
        ),
    ]
