# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_remove_pedido_bairro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='_bairro',
            new_name='bairro',
        ),
    ]
