# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_auto_20180205_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='nome_proprietario',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
