# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 01:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_auto_20180409_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
