# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_auto_20180412_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='zenvia_conta',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Conta Zenvia'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='zenvia_password',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Codigo Zenvia'),
        ),
    ]
