# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 11:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_auto_20180412_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'AVISO'), (1, 'HOME'), (2, 'PRODUTO'), (3, 'PEDIDO'), (4, 'PROMOCAO')])),
                ('titulo', models.CharField(max_length=50)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('visualizada', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='api.Cliente')),
            ],
        ),
    ]
