# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
