# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-28 10:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_cliente_fcm_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='valor_total',
            new_name='valor_bruto',
        ),
        migrations.AddField(
            model_name='farmacia',
            name='dia_faturamento',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20)], default=20, verbose_name='Dia de Faturamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_comissao_administradora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_comissao_thefarma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
    ]
