# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-01 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_auto_20180928_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_faturamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
