# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-02 10:09
from __future__ import unicode_literals

import api.models.enums.pagador_contas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_merge_20181001_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='pagador',
            field=models.IntegerField(choices=[(0, 'FARMACIA'), (1, 'ADMINISTRADORA')], default=api.models.enums.pagador_contas.PagadorContas(0)),
        ),
    ]
