# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_contareceber_pagador'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
