# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 10:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_pedido_valor_bruto_sem_frete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_bruto_sem_frete',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
