# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_auto_20181003_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
