# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_pedido_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
