# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_auto_20181004_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
