# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 18:52
from __future__ import unicode_literals

import api.models.enums.status_pedido_faturamento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_auto_20181016_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_faturamento',
            field=models.IntegerField(choices=[(0, 'NAO_FATURADO'), (1, 'FATURADO')], default=api.models.enums.status_pedido_faturamento.StatusPedidoFaturamento(0), null=True),
        ),
    ]
