# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_auto_20181101_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
