# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_auto_20181101_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
