# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 14:47
from __future__ import unicode_literals

import api.models.enums.status_pagamento_conta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_auto_20181101_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTA'), (1, 'PAGA'), (2, 'ATRASADA'), (3, 'CANCELADA')], default=api.models.enums.status_pagamento_conta.StatusPagamentoConta(0)),
        ),
    ]
