# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-19 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_auto_20181119_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='boleto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='data_emissao',
        ),
        migrations.AddField(
            model_name='conta',
            name='boleto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='api.Boleto'),
        ),
        migrations.AddField(
            model_name='conta',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
