# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_auto_20181119_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='boleto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta', to='api.Boleto'),
        ),
    ]
