# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-19 11:20
from __future__ import unicode_literals

import api.models.enums.status_pagamento_conta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_auto_20181119_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTA'), (1, 'FECHADA'), (2, 'PAGA'), (3, 'ATRASADA'), (4, 'CANCELADA')], default=api.models.enums.status_pagamento_conta.StatusPagamentoConta(0)),
        ),
    ]
