# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_auto_20181119_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='dia_faturamento',
        ),
        migrations.AddField(
            model_name='conta',
            name='data_faturamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='dia_pagamento',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20)], default=20, verbose_name='Dia de Pagamento'),
        ),
    ]
