# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-23 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_auto_20181120_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaFarmaceutica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=175)),
                ('medida_da_dosagem', models.CharField(max_length=175)),
            ],
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='dosagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='forma_farmaceutica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apresentacoes', to='api.FormaFarmaceutica'),
        ),
    ]
