# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-26 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_auto_20181123_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Sufixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
            ],
        ),
        migrations.RemoveField(
            model_name='formafarmaceutica',
            name='medida_da_dosagem',
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='comercializado',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='identificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='pbm',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='dosagem',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='forma_farmaceutica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes', to='api.FormaFarmaceutica'),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='formafarmaceutica',
            name='nome',
            field=models.CharField(max_length=75),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='embalagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes', to='api.Embalagem'),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='sufixo_dosagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_com_sufixo_dosagem', to='api.Sufixo', verbose_name='Sufixo da Dosagem'),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='sufixo_quantidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_com_sufixo_quantidade', to='api.Sufixo', verbose_name='Sufixo da Quantidade'),
        ),
    ]
