# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-28 08:47
from __future__ import unicode_literals

import api.models.apresentacao
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_auto_20181126_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.apresentacao.generate_filename),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='sufixo_quantidade',
            field=models.ForeignKey(blank=True, help_text='Não obrigatório', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_com_sufixo_quantidade', to='api.Sufixo', verbose_name='Sufixo da Quantidade'),
        ),
    ]
