# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-28 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_auto_20181128_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='embalagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes', to='api.Embalagem'),
        ),
    ]
