# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-29 03:41
from __future__ import unicode_literals

import api.models.apresentacao
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_auto_20181128_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='apresentacao_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='imagem',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=api.models.apresentacao.generate_apresentacao_filename),
        ),
    ]
