# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-30 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_auto_20181129_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='segunda_dosagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='sufixo_segunda_dosagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_com_sufixo_segunda_dosagem', to='api.Sufixo', verbose_name='Sufixo da Segunda Dosagem'),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='sufixo_terceira_dosagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_com_sufixo_teceira_dosagem', to='api.Sufixo', verbose_name='Sufixo da Terceira Dosagem'),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='terceira_dosagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
