# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-30 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_auto_20181130_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='pbm',
            field=models.BooleanField(default=False),
        ),
    ]
