# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_auto_20181219_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacoestemplate',
            name='tela',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacoestemplate',
            name='tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacoestemplate',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
