# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-20 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_auto_20181220_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='dosagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='sufixo_dosagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_com_sufixo_dosagem', to='api.Sufixo', verbose_name='Sufixo da Dosagem'),
        ),
    ]
