# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-27 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_ultimopreco'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='quarta_dosagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='sufixo_quarta_dosagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_com_sufixo_quarta_dosagem', to='api.Sufixo', verbose_name='Sufixo da Quarta Dosagem'),
        ),
    ]
