# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-10 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_auto_20190110_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='farmacias_receberam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
