# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-13 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_pedido_farmacias_receberam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacoestemplate',
            old_name='mensagem',
            new_name='menssagem',
        ),
    ]
