# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_auto_20190113_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='data_atualizacao_manual',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
