# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_precosugerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='pedido',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Pedido'),
        ),
    ]
