# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-12 14:40
from __future__ import unicode_literals

import api.models.enums.status_pedido
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_notificacao_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTO'), (1, 'ACEITO'), (2, 'AGUARDANDO_ENVIO_FARMACIA'), (3, 'AGUARDANDO_RETIRADA_CLIENTE'), (4, 'ENVIADO'), (5, 'ENTREGUE'), (6, 'CANCELADO_PELA_FARMACIA'), (7, 'CANCELADO_PELO_CLIENTE'), (8, 'SEM_PROPOSTA'), (9, 'TIMEOUT'), (10, 'NAO_ENTREGUE')], default=api.models.enums.status_pedido.StatusPedido(0)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_bruto_sem_frete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
