# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-13 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_auto_20190612_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='mensagem_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
