# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-13 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_notificacao_mensagem_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacoestemplate',
            name='mensagem_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
