# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-02 13:40
from __future__ import unicode_literals

import api.models.enums.status_pedido
import decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_notificacoestemplate_mensagem_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='raio_acao',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(0, 'ABERTO'), (1, 'ACEITO'), (2, 'AGUARDANDO_ENVIO_FARMACIA'), (3, 'AGUARDANDO_RETIRADA_CLIENTE'), (4, 'ENVIADO'), (5, 'ENTREGUE'), (6, 'CANCELADO_PELA_FARMACIA'), (7, 'CANCELADO_PELO_CLIENTE'), (8, 'SEM_PROPOSTA'), (9, 'TIMEOUT'), (10, 'NAO_ENTREGUE'), (11, 'ESTORNADO')], default=api.models.enums.status_pedido.StatusPedido(0)),
        ),
    ]
