# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-10 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_auto_20190702_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempropostapedido',
            unique_together=set([]),
        ),
    ]
