# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-18 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_auto_20190710_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempropostapedido',
            name='permutacao_id',
            field=models.IntegerField(default=0),
        ),
    ]
