# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-19 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_notificacao_farmacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.NotificacoesTemplate'),
        ),
    ]
