# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_notificacao_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='aceita_generico',
            field=models.BooleanField(default=False),
        ),
    ]
