# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_itempedido_aceita_generico'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempropostapedido',
            name='apresentacao_pedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Apresentacao'),
        ),
    ]
